
all: jquery.js jquery.simplemodal-1.3.3.min.js json2.js pidcrypt/pidcrypt.js pidcrypt/pidcrypt_util.js pidcrypt/md5.js pidcrypt/aes_core.js pidcrypt/aes_cbc.js
	cat jquery.js jquery.simplemodal-1.3.3.min.js json2.js pidcrypt/pidcrypt.js pidcrypt/pidcrypt_util.js pidcrypt/md5.js pidcrypt/aes_core.js pidcrypt/aes_cbc.js \
	  | python ./jsmin.py > all-min.js

